title: Identifying snippets of relevant documentation for newcomers in open source projects
email: fronchettl@vcu.edu
description: This is a replication package provided by Felipe Fronchetti.
github_username: fronchetti
baseurl: /USP-2020
repository: https://github.com/fronchetti/USP-2020

collections:
  stages:
    output: true
    permalink: /:collection/:name
    order:
      - overview.md
      - stage-one.md
      - stage-two.md
      - stage-three.md

plugins:
  - jekyll-toc
